spring.application.name=demo
qwen.apiKey=${DASHSCOPE_API_KEY:}
spring.datasource.url=jdbc:mysql://localhost:3306/ai_recruitment_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=${DATASOURCE_PASSWORD:}
mybatis.configuration.map-underscore-to-camel-case=true
